### ISSUE TITLE
editing the add_text_input after creating it

### ISSUE THREAD

**Issue by mikeporetti** [jchanvfx/NodeGraphQt#136]
nevermind i was able to do this by:

        for name, widget in self.view.widgets.items():
            self.text_edit = widget.widget

**Comment by jchanvfx** [comment]
Hi @mikeporetti 

There's a `text` arg in the `add_text_input` method when you can have pre filled text for the widget:
https://jchanvfx.github.io/NodeGraphQt/api/html/nodes/BaseNode.html#NodeGraphQt.BaseNode.add_text_input

or instead of editing the widget you should set the node property that way it'll registered as part of an undo command.

```python
class MyNode(BaseNode):

    __identifier__ = 'com.chantasticvfx'
    NODE_NAME = 'node'

    def __init__(self):
        super(MyNode, self).__init__()
        self.add_text_input('my_text', 'My Text Title', 'my profiled text')
        
        # Set the property this'll register as an undo and update the widget.
        self.set_property('my_text', 'foo bar')
```

Cheers,
Johnny
