### ISSUE TITLE
Is this module python 2 compatible

### ISSUE THREAD

**Issue by IdrisMiles** [jchanvfx/NodeGraphQt#187]
Hello, I'm wondering if this package is using any features that are not python 2 compatible?

I'm working on a project that is supporting python 2 & 3 still, and would like to add this module to the requirements however the `setup.py` is pinning the package to 3.6, is there any reason it couldn't include python 2.7 in the setup.py?

**Comment by jchanvfx** [comment]
Hi @IdrisMiles,

You can use it with python 2.7 but there maybe be some tweaks you'll have to make to the qgraphics items code.

if I remember correctly one of them was that the node ports would be initialized in a random order because dictionaries in python 2 is not ordered by default.
https://github.com/jchanvfx/NodeGraphQt/blob/39f1f9d8c8a8d7380ef550b36c76268f65a6a27b/NodeGraphQt/qgraphics/node_base.py#L133-L134

**Comment by IdrisMiles** [comment]
ah good to know, I don't think that's a problem for my use case, thanks for the respone!
