### ISSUE TITLE
Exception: Cannot find node: "nodeGraphQt.nodes.Backdrop" when creating backdrop node

### ISSUE THREAD

**Issue by generic-github-user** [jchanvfx/NodeGraphQt#220]
I am currently running (unmodified) the simple example from https://jchanvfx.github.io/NodeGraphQt/api/html/examples/ex_overview.html#simple-example. This results in an Exception:
```
>> Cannot find node:	"nodeGraphQt.nodes.Backdrop"
```
I should also note that I implemented the quick fix from https://github.com/jchanvfx/NodeGraphQt/issues/212#issuecomment-842476078 after encountering an import issue in the `__init__` script; this could be a factor. I installed via pip from the cloned repo and am running the example in a Jupyter (IPython) notebook.

**Comment by generic-github-user** [comment]
I tried removing the lines using the backdrop node, which led to the IPython kernel crashing on execution - however, this has not been consistent and the application sometimes loads without issue.

**Comment by mara004** [comment]
I think `nodeGraphQt` is simply misspelled; should be `NodeGraphQt`.

**Comment by mara004** [comment]
I think `from NodeGraphQt import BackdropNode` should work.

**Comment by sc420** [comment]
I encountered the same error. After some debugging I found that the current [example code](https://github.com/jchanvfx/NodeGraphQt#example) on GitHub is actually wrong.

Changing the line
`backdrop = graph.create_node('nodeGraphQt.nodes.Backdrop', name='Backdrop')`
to
`backdrop = graph.create_node('nodeGraphQt.nodes.BackdropNode', name='Backdrop')`
will work.

Or even better:
`backdrop = graph.create_node(BackdropNode.type_, name='Backdrop')`

Reason: Since `type_` of a node [is composed of](https://github.com/jchanvfx/NodeGraphQt/blob/0.1.7/NodeGraphQt/base/node.py#L84) the identifier and the class name. `BackdropNode` is registered with type `nodeGraphQt.nodes.BackdropNode`.
