### ISSUE TITLE
ImportError: No Qt binding were found.

### ISSUE THREAD

**Issue by lihuaiguang** [jchanvfx/NodeGraphQt#230]
Hi, I have the following error:

----
NodeGraphQt % python3 example_auto_nodes.py

Traceback (most recent call last):
  File "example_auto_nodes.py", line 3, in <module>
    from NodeGraphQt import NodeGraph, setup_context_menu, \
  File "/Users/atx/Documents/Python/2021-NodeGraphQt/NodeGraphQt/__init__.py", line 76, in <module>
    from .base.graph import NodeGraph, SubGraph
  File "/Users/atx/Documents/Python/2021-NodeGraphQt/NodeGraphQt/base/graph.py", line 9, in <module>
    from Qt import QtCore, QtWidgets, QtGui
  File "/Users/atx/Documents/Python/2021-NodeGraphQt/docs/testenv/lib/python3.6/site-packages/Qt.py-1.3.6-py3.6.egg/Qt.py", line 1928, in <module>
    _install()
  File "/Users/atx/Documents/Python/2021-NodeGraphQt/docs/testenv/lib/python3.6/site-packages/Qt.py-1.3.6-py3.6.egg/Qt.py", line 1876, in _install
    raise ImportError("No Qt binding were found.")
ImportError: No Qt binding were found.

---
MacOS 11.5.2, Python 3.6

**Comment by infintropy** [comment]
Make sure you have Qt libraries at hand on your Mac.  In your `testenv` make sure you:
```bash
pip install PySide2
``` 
which would then be called by Qt.py as an available lib to import.

**Comment by mara004** [comment]
@infintropy is right. `Qt.py`, the abstraction layer for `PySide2`/`PyQt5` used by NodeGraphQt, requires at least one of these two Qt bindings to be installed. Simply install the one of your preference with the Python package manager `pip3`.
I would generally recommend PySide since it is officially supported by The Qt Company and the licensing model is more liberal than the one of PyQt.

**Comment by lihuaiguang** [comment]
Thanks, @mara004, for the suggestion! 
After try to install the pyside2, I find a new error msg while running:

% python3 example.py              
Error in importing class: cannot import name 'QtCore' from 'NodeGraphQt' (/Users/atx/Documents/Python/2021-NodeGraphQt/NodeGraphQt/__init__.py)

Anything wrong?

**Comment by mara004** [comment]
I can reproduce the error message. However, the GUI still shows up correctly for me.
There is one spot in `example_auto_nodes/input_nodes.py` where QtCore is wrongly imported from NodeGraphQt, but changing it did not fix the error messages.
The related code apparently is `getNodesRecursively()` in `NodeGraphQt.__init__`. Unfortuantely it's a bit hard to tell where the root cause of these errors is without having deeper insights into the code.

**Comment by matsbohlinsson** [comment]
> I can reproduce the error message. However, the GUI still shows up correctly for me.
> There is one spot in `example_auto_nodes/input_nodes.py` where QtCore is wrongly imported from NodeGraphQt, but changing it did not fix the error messages.
> The related code apparently is `getNodesRecursively()` in `NodeGraphQt.__init__`. Unfortuantely it's a bit hard to tell where the root cause of these errors is without having deeper insights into the code.

Same problem.

**Comment by mara004** [comment]
Yeah, and a similar issue exists for the math nodes example (which seems a little bit broken in general...)

**Comment by ClaireLush** [comment]
I have the same issue and cannot install into Python as part of QGIS. It already has PyQt5 but it doesn't work.
